-- MySQL Script generated by MySQL Workbench
-- Thu Apr 26 10:43:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TPCCustShrunk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TPCCustShrunk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TPCCustShrunk` DEFAULT CHARACTER SET latin1 ;
USE `TPCCustShrunk` ;

-- -----------------------------------------------------
-- Table `TPCCustShrunk`.`Customer_State_Dimension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TPCCustShrunk`.`Customer_State_Dimension` (
  `Customer State SK(PK)` INT(11) NOT NULL,
  `Customer State ID(NK)` INT NULL DEFAULT NULL,
  `Customer State` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`Customer State SK(PK)`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TPCCustShrunk`.`Order_Date_Dimension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TPCCustShrunk`.`Order_Date_Dimension` (
  `Order Date SK(PK)` INT(11) NOT NULL,
  `orderDate` DATE NULL DEFAULT NULL,
  `Year` YEAR(4) NULL DEFAULT NULL,
  `Quarter` VARCHAR(1) NULL DEFAULT NULL,
  `Month` VARCHAR(2) NULL DEFAULT NULL,
  `Day` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`Order Date SK(PK)`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TPCCustShrunk`.`Order_Indicator_Dimension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TPCCustShrunk`.`Order_Indicator_Dimension` (
  `Order Indicator SK(PK)` INT(11) NOT NULL,
  `Ordering Method` VARCHAR(45) NULL DEFAULT NULL,
  `Payment Method` VARCHAR(45) NULL DEFAULT NULL,
  `Shipping Method` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Order Indicator SK(PK)`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TPCCustShrunk`.`Product_Dimension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TPCCustShrunk`.`Product_Dimension` (
  `Product SK(PK)` INT(11) NOT NULL,
  `TPCW Product ID(NK)` INT NULL DEFAULT NULL,
  `TPCE Product ID(NK)` INT NULL DEFAULT NULL,
  `PEC Product ID(NK)` INT NULL DEFAULT NULL,
  `Product Description` VARCHAR(50) NULL DEFAULT NULL,
  `Product Price 1` DECIMAL(15,2) NULL DEFAULT NULL,
  `Product Price 2` DECIMAL(15,2) NULL DEFAULT NULL,
  `TPCW-E Product Unit Cost` DECIMAL(15,2) NULL DEFAULT NULL,
  `PEC Product Unit Cost` DECIMAL(15,2) NULL DEFAULT NULL,
  `Product TypeID` INT NULL DEFAULT NULL,
  `Product Type Description` VARCHAR(45) NULL DEFAULT NULL,
  `Business Unit ID` VARCHAR(1) NULL DEFAULT NULL,
  `Business Unit Name` VARCHAR(25) NULL DEFAULT NULL,
  `Business Abbrev` VARCHAR(15) NULL DEFAULT NULL,
  `Version` VARCHAR(20) NULL DEFAULT NULL,
  `Start Date` DATE NULL DEFAULT NULL,
  `End Date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Product SK(PK)`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TPCCustShrunk`.`Sales_Date_Dimension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TPCCustShrunk`.`Sales_Date_Dimension` (
  `Sales Date SK(PK)` INT(11) NOT NULL,
  `salesDate` DATE NULL DEFAULT NULL,
  `Year` YEAR(4) NULL DEFAULT NULL,
  `Quarter` VARCHAR(1) NULL DEFAULT NULL,
  `Month` VARCHAR(2) NULL DEFAULT NULL,
  `Day` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`Sales Date SK(PK)`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TPCCustShrunk`.`Supplier_Dimension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TPCCustShrunk`.`Supplier_Dimension` (
  `Supplier SK(PK)` INT(11) NOT NULL,
  `Supplier ID (NK)` INT NULL,
  `Supplier Name` VARCHAR(45) NULL DEFAULT NULL,
  `Supplier Address 1` VARCHAR(50) NULL DEFAULT NULL,
  `Supplier Address 2` VARCHAR(50) NULL DEFAULT NULL,
  `Supplier City` VARCHAR(20) NULL DEFAULT NULL,
  `Supplier State` VARCHAR(2) NULL DEFAULT NULL,
  `Supplier ZipCode` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`Supplier SK(PK)`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TPCCustShrunk`.`Financial_Analysis_Fact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TPCCustShrunk`.`Financial_Analysis_Fact` (
  `Customer State SK(FK)` INT(11) NOT NULL,
  `Supplier SK(FK)` INT(11) NOT NULL,
  `Product SK(FK)` INT(11) NOT NULL,
  `Order Date SK(FK)` INT(11) NOT NULL,
  `Sales Date SK(FK)` INT(11) NOT NULL,
  `Order Indicator SK(FK)` INT(11) NOT NULL,
  `Number of days` INT NULL DEFAULT NULL,
  `shipCost` DECIMAL(10,2) NULL DEFAULT NULL,
  `Amount` DECIMAL(10,2) NULL DEFAULT NULL,
  `Quantity` INT(11) NULL DEFAULT NULL,
  `Discounted` INT NULL DEFAULT NULL,
  `Invoice ID(DD)` INT NULL DEFAULT NULL,
  `Source` VARCHAR(10) NULL,
  INDEX `fk_Financial_Analysis_Fact_Supplier_Dimension1_idx` (`Supplier SK(FK)` ASC),
  INDEX `fk_Financial_Analysis_Fact_Customer_Dimension1_idx` (`Customer State SK(FK)` ASC),
  INDEX `fk_Financial_Analysis_Fact_Order_Date_Dimension1_idx` (`Order Date SK(FK)` ASC),
  INDEX `fk_Financial_Analysis_Fact_Sales_Date_Dimension1_idx` (`Sales Date SK(FK)` ASC),
  INDEX `fk_Financial_Analysis_Fact_Product_Dimension1_idx` (`Product SK(FK)` ASC),
  INDEX `fk_Financial_Analysis_Fact_Payment_Method_Dimension` (`Order Indicator SK(FK)` ASC),
  CONSTRAINT `fk_Financial_Analysis_Fact_Customer_Dimension1`
    FOREIGN KEY (`Customer State SK(FK)`)
    REFERENCES `TPCCustShrunk`.`Customer_State_Dimension` (`Customer State SK(PK)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Financial_Analysis_Fact_Order_Date_Dimension1`
    FOREIGN KEY (`Order Date SK(FK)`)
    REFERENCES `TPCCustShrunk`.`Order_Date_Dimension` (`Order Date SK(PK)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Financial_Analysis_Fact_Payment_Method_Dimension`
    FOREIGN KEY (`Order Indicator SK(FK)`)
    REFERENCES `TPCCustShrunk`.`Order_Indicator_Dimension` (`Order Indicator SK(PK)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Financial_Analysis_Fact_Product_Dimension1`
    FOREIGN KEY (`Product SK(FK)`)
    REFERENCES `TPCCustShrunk`.`Product_Dimension` (`Product SK(PK)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Financial_Analysis_Fact_Sales_Date_Dimension1`
    FOREIGN KEY (`Sales Date SK(FK)`)
    REFERENCES `TPCCustShrunk`.`Sales_Date_Dimension` (`Sales Date SK(PK)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Financial_Analysis_Fact_Supplier_Dimension1`
    FOREIGN KEY (`Supplier SK(FK)`)
    REFERENCES `TPCCustShrunk`.`Supplier_Dimension` (`Supplier SK(PK)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
