-- MySQL Script generated by MySQL Workbench
-- Sat Apr 28 17:03:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TPCDataMart
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TPCDataMart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TPCDataMart` DEFAULT CHARACTER SET latin1 ;
USE `TPCDataMart` ;

-- -----------------------------------------------------
-- Table `TPCDataMart`.`Customer_Dimension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TPCDataMart`.`Customer_Dimension` (
  `Customer SK` INT(11) NOT NULL,
  `TPCW Customer ID(NK)` INT(11) NULL DEFAULT NULL,
  `TPCE Customer ID(NK)` INT(11) NULL DEFAULT NULL,
  `PEC Customer ID(NK)` INT(11) NULL DEFAULT NULL,
  `Customer Name` VARCHAR(55) NULL DEFAULT NULL,
  `Customer Address 1` VARCHAR(50) NULL DEFAULT NULL,
  `Customer Address 2` VARCHAR(50) NULL DEFAULT NULL,
  `Customer City` VARCHAR(25) NULL DEFAULT NULL,
  `Customer State` VARCHAR(2) NULL DEFAULT NULL,
  `Customer Zipcode` VARCHAR(5) NULL DEFAULT NULL,
  `Customer Type ID` VARCHAR(1) NULL DEFAULT NULL,
  `Customer Type Name` VARCHAR(20) NULL DEFAULT NULL,
  `Version` VARCHAR(20) NULL DEFAULT NULL,
  `Start Date` DATE NULL DEFAULT NULL,
  `End Date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Customer SK`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TPCDataMart`.`Order_Date_Dimension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TPCDataMart`.`Order_Date_Dimension` (
  `Order Date SK` INT(11) NOT NULL,
  `orderDate` DATE NULL DEFAULT NULL,
  `Year` YEAR(4) NULL DEFAULT NULL,
  `Quarter` VARCHAR(1) NULL DEFAULT NULL,
  `Month` VARCHAR(2) NULL DEFAULT NULL,
  `Day` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`Order Date SK`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TPCDataMart`.`Order_Indicator_Dimension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TPCDataMart`.`Order_Indicator_Dimension` (
  `Order Indicator SK` INT(11) NOT NULL,
  `Ordering Method` VARCHAR(45) NULL DEFAULT NULL,
  `Payment Method` VARCHAR(45) NULL DEFAULT NULL,
  `Shipping Method` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Order Indicator SK`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TPCDataMart`.`Product_Dimension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TPCDataMart`.`Product_Dimension` (
  `Product SK` INT(11) NOT NULL,
  `TPCW Product ID(NK)` INT(11) NULL DEFAULT NULL,
  `TPCE Product ID(NK)` INT(11) NULL DEFAULT NULL,
  `PEC Product ID(NK)` INT(11) NULL DEFAULT NULL,
  `Product Description` VARCHAR(50) NULL DEFAULT NULL,
  `Product Price 1` DECIMAL(15,2) NULL DEFAULT NULL,
  `Product Price 2` DECIMAL(15,2) NULL DEFAULT NULL,
  `TPCW-E Product Unit Cost` DECIMAL(15,2) NULL DEFAULT NULL,
  `PEC Product Unit Cost` DECIMAL(15,2) NULL DEFAULT NULL,
  `Product TypeID` INT(11) NULL DEFAULT NULL,
  `Product Type Description` VARCHAR(45) NULL DEFAULT NULL,
  `Business Unit ID` VARCHAR(1) NULL DEFAULT NULL,
  `Business Unit Name` VARCHAR(25) NULL DEFAULT NULL,
  `Business Abbrev` VARCHAR(15) NULL DEFAULT NULL,
  `Version` VARCHAR(20) NULL DEFAULT NULL,
  `Start Date` DATE NULL DEFAULT NULL,
  `End Date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Product SK`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TPCDataMart`.`Sales_Date_Dimension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TPCDataMart`.`Sales_Date_Dimension` (
  `Sales Date SK` INT(11) NOT NULL,
  `salesDate` DATE NULL DEFAULT NULL,
  `Year` YEAR(4) NULL DEFAULT NULL,
  `Quarter` VARCHAR(1) NULL DEFAULT NULL,
  `Month` VARCHAR(2) NULL DEFAULT NULL,
  `Day` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`Sales Date SK`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TPCDataMart`.`Supplier_Dimension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TPCDataMart`.`Supplier_Dimension` (
  `Supplier SK` INT(11) NOT NULL,
  `Supplier ID (NK)` INT(11) NULL DEFAULT NULL,
  `Supplier Name` VARCHAR(45) NULL DEFAULT NULL,
  `Supplier Address 1` VARCHAR(50) NULL DEFAULT NULL,
  `Supplier Address 2` VARCHAR(50) NULL DEFAULT NULL,
  `Supplier City` VARCHAR(20) NULL DEFAULT NULL,
  `Supplier State` VARCHAR(2) NULL DEFAULT NULL,
  `Supplier ZipCode` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`Supplier SK`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TPCDataMart`.`Financial_Analysis_Fact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TPCDataMart`.`Financial_Analysis_Fact` (
  `Customer SK` INT(11) NOT NULL,
  `Supplier SK` INT(11) NOT NULL,
  `Product SK` INT(11) NOT NULL,
  `Order Date SK` INT(11) NOT NULL,
  `Sales Date SK` INT(11) NOT NULL,
  `Order Indicator SK` INT(11) NOT NULL,
  `Number of days` INT(11) NULL DEFAULT NULL,
  `shipCost` DECIMAL(10,2) NULL DEFAULT NULL,
  `Amount` DECIMAL(10,2) NULL DEFAULT NULL,
  `Quantity` INT(11) NULL DEFAULT NULL,
  `Discounted` INT(11) NULL DEFAULT NULL,
  `InvoiceID_DD` INT(11) NULL DEFAULT NULL,
  `Source` VARCHAR(10) NULL DEFAULT NULL,
  INDEX `fk_Financial_Analysis_Fact_Supplier_Dimension1_idx` (`Supplier SK` ASC),
  INDEX `fk_Financial_Analysis_Fact_Customer_Dimension1_idx` (`Customer SK` ASC),
  INDEX `fk_Financial_Analysis_Fact_Order_Date_Dimension1_idx` (`Order Date SK` ASC),
  INDEX `fk_Financial_Analysis_Fact_Sales_Date_Dimension1_idx` (`Sales Date SK` ASC),
  INDEX `fk_Financial_Analysis_Fact_Product_Dimension1_idx` (`Product SK` ASC),
  INDEX `fk_Financial_Analysis_Fact_Payment_Method_Dimension` (`Order Indicator SK` ASC),
  PRIMARY KEY (`Customer SK`, `Product SK`, `Order Indicator SK`, `Supplier SK`, `Order Date SK`, `Sales Date SK`),
  CONSTRAINT `fk_Financial_Analysis_Fact_Customer_Dimension1`
    FOREIGN KEY (`Customer SK`)
    REFERENCES `TPCDataMart`.`Customer_Dimension` (`Customer SK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Financial_Analysis_Fact_Order_Date_Dimension1`
    FOREIGN KEY (`Order Date SK`)
    REFERENCES `TPCDataMart`.`Order_Date_Dimension` (`Order Date SK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Financial_Analysis_Fact_Payment_Method_Dimension`
    FOREIGN KEY (`Order Indicator SK`)
    REFERENCES `TPCDataMart`.`Order_Indicator_Dimension` (`Order Indicator SK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Financial_Analysis_Fact_Product_Dimension1`
    FOREIGN KEY (`Product SK`)
    REFERENCES `TPCDataMart`.`Product_Dimension` (`Product SK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Financial_Analysis_Fact_Sales_Date_Dimension1`
    FOREIGN KEY (`Sales Date SK`)
    REFERENCES `TPCDataMart`.`Sales_Date_Dimension` (`Sales Date SK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Financial_Analysis_Fact_Supplier_Dimension1`
    FOREIGN KEY (`Supplier SK`)
    REFERENCES `TPCDataMart`.`Supplier_Dimension` (`Supplier SK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
